### ISSUE TITLE
RichMedia preview is not available.

### ISSUE THREAD

**Issue by Erwin-Kation** [SmartloopAI/smartloop-feedback#13] opened 2020-06-19 06:33 UTC
**Describe the bug**
When showing cards with images in viber on IOS, users are getting the message RichMedia preview is not available..

**Which platform(s) does the issue occur on**
Viber

**Does this issue happen every time?**
No

**To Reproduce**
Images from Card are retrieved from an API call

**Expected behavior**
Display Cards with Images

**Additional context**

**Comment by mehfuzh** [comment] 2020-06-20 23:56
This is only in the live chat section, Users do see it  in the Viber bot

**Comment by mehfuzh** [comment] 2020-06-20 23:56
Duplicate of #14

**Closed by mehfuzh** 2020-06-20 23:56 UTC
