### ISSUE TITLE
Error with Collaborator function

### ISSUE THREAD

**Issue by rt1010** [SmartloopAI/smartloop-feedback#6] opened 2020-06-14 12:04 UTC
Any email I type, bring up an "Please invite a user with email who have a valid account!" error

**Comment by mehfuzh** [comment] 2020-06-14 18:53
You will need that other person to have an account on smartloop but this is a good point.

**Comment by mehfuzh** [comment] 2020-06-21 19:53
Duplicate of #15

**Closed** 2020-06-21 19:53 UTC
Labels: review
